In [1]:
import numpy as np

In [4]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'E:/Anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'E:/Anaconda\\Library\\include']

In [5]:
zero10 = np.zeros(10)
print(zero10)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [6]:
print("%d bytes"%(zero10.size * zero10.itemsize))

80 bytes


In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
x1 = np.arange(9.0).reshape((3, 3))
x1

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [9]:
x2 = np.arange(3.0)
x2

array([ 0.,  1.,  2.])

In [10]:
array = np.zeros(10)
array[4] = 1
print(array)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


In [13]:
array = np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
array = np.random.randint(10,50,5)
print(array)

[49 30 19 33 34]


In [17]:
array[::-1]

array([34, 33, 19, 30, 49])

In [19]:
array = np.arange(9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
array = np.array([1,2,0,0,4,0])
array.nonzero()

(array([0, 1, 4], dtype=int64),)

In [30]:
array = np.eye(3)
print(array)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
array = np.random.randint(0,27,(3,3,3))
print(array)

[[[ 6  4 19]
  [ 2  9 24]
  [14  7  5]]

 [[ 8 15 24]
  [ 9 12 23]
  [16  9  9]]

 [[ 5 23  8]
  [ 2  5  8]
  [19 25  3]]]


In [35]:
array = np.random.random((3,3,3))
print(array)

[[[ 0.61461677  0.10496687  0.10154102]
  [ 0.94469918  0.91018683  0.35286974]
  [ 0.38124596  0.38410269  0.33976454]]

 [[ 0.82639288  0.29056705  0.11678092]
  [ 0.50840928  0.88744336  0.10996296]
  [ 0.49853774  0.71086958  0.36541637]]

 [[ 0.61027105  0.0052585   0.68793759]
  [ 0.81603167  0.0406712   0.09714689]
  [ 0.71161843  0.08158501  0.94704828]]]


In [38]:
array = np.random.random((10,10))
ma = array.max()
mi = array.min()
print("max = %f ,min = %f"%(ma,mi))

max = 0.986151 ,min = 0.012427


In [40]:
array = np.random.random(30)
mean = array.mean()
print(mean)

0.540448991925


In [41]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [49]:
array = np.random.randint(0,5,(5,5))
array = np.pad(array,((1,1),(1,1)),'constant',constant_values = (0,0))
print(array)

[[0 0 0 0 0 0 0]
 [0 2 2 1 2 2 0]
 [0 2 3 2 0 2 0]
 [0 0 4 0 2 4 0]
 [0 2 2 0 0 3 0]
 [0 0 4 1 3 1 0]
 [0 0 0 0 0 0 0]]


In [50]:
0*np.nan

nan

In [51]:
np.nan == np.nan

False

In [52]:
np.inf > np.nan

False

In [54]:
np.nan - np.nan

nan

In [55]:
3 * 0.1

0.30000000000000004

In [56]:
0.3 == 3 * 0.1

False

In [57]:
array = np.diag([1,2,3,4],k=-1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [58]:
 Z = np.zeros((8,8),dtype=int)
 Z[1::2,::2] = 1
 Z[::2,1::2] = 1
 print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [60]:
array = np.random.random((5,5))
amax = array.max()
amin = array.min()
array = (array-amin)/(amax-amin)
print(array)

[[ 0.62357329  0.02468411  0.30563033  0.45444194  0.49168168]
 [ 0.17407709  0.43123762  0.61658777  0.89703665  0.43368626]
 [ 0.72118723  0.24099658  0.98845097  0.          0.62520514]
 [ 0.20126041  0.58048711  0.05637012  0.6851514   0.05784004]
 [ 0.53049821  0.59686905  0.79859831  0.76999157  1.        ]]


In [61]:
array1 = np.random.randint(1,4,(5,3))
array2 = np.random.randint(1,4,(3,2))
array1.dot(array2)

array([[12, 10],
       [ 8,  7],
       [ 8, 12],
       [13, 15],
       [ 9, 10]])

In [68]:
array = np.random.randint(1,11,(5,3))
print(array)
array[(3<=array) & (array<8)] *= -1
print(array)

[[4 9 8]
 [4 6 6]
 [9 1 1]
 [8 2 8]
 [3 2 8]]
[[-4  9  8]
 [-4 -6 -6]
 [ 9  1  1]
 [ 8  2  8]
 [-3  2  8]]


In [82]:
print(sum(range(5),-1))

10


In [81]:
print(np.sum(range(5),-1))

10


In [89]:
a = np.array([1,2,3])
2 << a >> 2

array([1, 2, 4], dtype=int32)

In [90]:
print(np.array(0) // np.array(0))

0


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [91]:
print(np.array(0) / np.array(0))

nan


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [92]:
np.array([np.nan]).astype(int).astype(float)

array([ -2.14748365e+09])

In [93]:
np.sqrt(-1) == np.emath.sqrt(-1)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [94]:
 np.emath.sqrt(-1)

1j

In [95]:
np.sqrt(-1)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [100]:
np.info(np.random.uniform)
array = np.random.uniform(-10,+10,10)
print(array)
print(np.copysign(np.ceil(np.abs(array)),array))

uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than high.  The default value is 1.0.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``low`` and ``high`` are both scalars.
    Otherwise, ``np.broadcast(low, high).size`` samples are drawn.

Returns
-------
out : ndarray or s

In [103]:
np.info(np.intersect1d)
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

 intersect1d(ar1, ar2, assume_unique=False)

Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.

Parameters
----------
ar1, ar2 : array_like
    Input arrays.
assume_unique : bool
    If True, the input arrays are both assumed to be unique, which
    can speed up the calculation.  Default is False.

Returns
-------
intersect1d : ndarray
    Sorted 1D array of common and unique elements.

See Also
--------
numpy.lib.arraysetops : Module with a number of other functions for
                        performing set operations on arrays.

Examples
--------
>>> np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])
array([1, 3])

To intersect more than two arrays, use functools.reduce:

>>> from functools import reduce
>>> reduce(np.intersect1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
array([3])
[4 6 7 8 9]


In [108]:
yesterday = np.datetime64('today','D')-np.timedelta64(1,"D")
print(yesterday)
today = np.datetime64("today","D")
print(today)
tomorrow = np.datetime64('today',"D") + np.timedelta64(1,"D")
print(tomorrow)

2019-06-22
2019-06-23
2019-06-24


In [110]:
array = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(array)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [115]:
array = np.random.uniform(0,10,10)
print(array - array%1)
print(np.floor(array))
print(np.ceil(array)-1)
print(array.astype(int))
print(np.trunc(array))

[ 4.  0.  4.  0.  9.  3.  7.  2.  3.  0.]
[ 4.  0.  4.  0.  9.  3.  7.  2.  3.  0.]
[ 4.  0.  4.  0.  9.  3.  7.  2.  3.  0.]
[4 0 4 0 9 3 7 2 3 0]
[ 4.  0.  4.  0.  9.  3.  7.  2.  3.  0.]


In [116]:
array = np.random.randint(0,5,(5,5))
print(array)

[[0 3 3 4 4]
 [0 1 3 1 4]
 [0 0 3 1 4]
 [4 2 2 0 3]
 [2 4 3 1 0]]


In [118]:
np.info(np.linspace)
array = np.linspace(0,1,11,endpoint = False)[1:]
print(array)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dtype : dtype, optional
    The type of the ou

In [119]:
np.sort(np.random.random(10))

array([ 0.06116989,  0.10433245,  0.18974493,  0.23858464,  0.56429218,
        0.89433302,  0.89896323,  0.91110877,  0.92133084,  0.96770173])

In [120]:
ar = np.arange(10)
np.add.reduce(ar)

45

In [122]:
ar1 = np.arange(9).reshape(3,3)
ar2 = np.arange(9).reshape(3,3)
eq = np.allclose(ar1,ar2)
eq1 = np.array_equal(ar1,ar2)
print(eq,eq1)

True True


In [124]:
ar = np.eye(3)
ar.flags.writeable = False
print(ar)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [125]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


In [133]:
ar = np.random.random(10)+3
print(ar)
ar = ar.astype(np.int32,copy = False)
print(ar)

[ 3.55163693  3.66702862  3.35216547  3.32827893  3.59350908  3.13455505
  3.14304885  3.01255685  3.97157631  3.7101731 ]
[3 3 3 3 3 3 3 3 3 3]


In [135]:
x,y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x + y*y)
sigma,mu = 1.0,0.0
g = np.exp(-((d-mu)**2 / (2.0 * sigma ** 2)))
print(g)

[[ 0.36787944  0.44822088  0.51979489  0.57375342  0.60279818  0.60279818
   0.57375342  0.51979489  0.44822088  0.36787944]
 [ 0.44822088  0.54610814  0.63331324  0.69905581  0.73444367  0.73444367
   0.69905581  0.63331324  0.54610814  0.44822088]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.60279818  0.73444367  0.85172308  0.9401382   0.98773022  0.98773022
   0.9401382   0.85172308  0.73444367  0.60279818]
 [ 0.57375342  0.69905581  0.81068432  0.89483932  0.9401382   0.9401382
   0.89483932  0.81068432  0.69905581  0.57375342]
 [ 0.51979489  0.63331324  0.73444367  0.81068432  0.85172308  0.85172308
   0.81068432  0.73444367  0.63331324  0.51979489]
 [

In [139]:
n = 10
p = 30
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[ 0.  0.  0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  1.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  1.  0.  0.  1.  0.  1.  1.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  1.  1.  1.  0.]
 [ 1.  1.  0.  0.  0.  1.  1.  0.  0.  0.]]


In [140]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.14309835  0.2815789   0.28225287  0.46173663 -0.34577806 -0.40385555
   0.08644254  0.2169483  -0.48905155 -0.23337241]
 [ 0.21804624 -0.43644848  0.20497408  0.3283175  -0.02608412  0.35918276
  -0.46075831 -0.11898951  0.37632845 -0.4445686 ]
 [ 0.03061854  0.03581673 -0.22746431  0.36333261  0.48015887 -0.41820648
  -0.01100353 -0.11008695 -0.00223136 -0.14093411]
 [-0.24639835  0.01253029  0.26041997  0.42513617 -0.29695898 -0.02279182
  -0.1869306   0.35234023 -0.15602078 -0.14132613]
 [ 0.11332672 -0.35416458 -0.34423639  0.00528892  0.18280199  0.20684414
  -0.00269709 -0.17334981  0.3300471   0.036139  ]]
