In [3]:
import pandas as pd

In [2]:
obj = pd.Series([1,3,5,7])
print(obj)

0    1
1    3
2    5
3    7
dtype: int64


In [4]:
obj.values

array([1, 3, 5, 7], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
obj2 = pd.Series([1,3,5,7],index=['a','b','c','d'])
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [9]:
obj2['a']

1

In [11]:
obj[[True,False,True,True]]

0    1
2    5
3    7
dtype: int64

In [13]:
obj2[['b','c','d','a']]

b    3
c    5
d    7
a    1
dtype: int64

In [14]:
obj2*2

a     2
b     6
c    10
d    14
dtype: int64

In [15]:
sdata = {'lizhi':100,'zhangweiwei':200,'wangfeng':300}

In [17]:
obj3 = pd.Series(sdata)
print(obj3)

lizhi          100
wangfeng       300
zhangweiwei    200
dtype: int64


In [28]:
name = ['lizhi','zhangweiwei','python']
obj4 = pd.Series(sdata,index = name)
obj4

lizhi          100.0
zhangweiwei    200.0
python           NaN
dtype: float64

In [26]:
pd.isnull(obj4)

lizhi         False
zhangweiei     True
python         True
dtype: bool

In [27]:
pd.notnull(obj4)

lizhi          True
zhangweiei    False
python        False
dtype: bool

In [24]:
obj3+obj4

c++              NaN
lizhi          200.0
python           NaN
wangfeng         NaN
zhangweiwei      NaN
dtype: float64

In [29]:
obj4.name = 'singer'
obj4.index.name = 'blv'
obj4

blv
lizhi          100.0
zhangweiwei    200.0
python           NaN
Name: singer, dtype: float64

In [31]:
data = {'state':['ohio','ohio','ohio','nevada','nevada','nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002
5  3.2  nevada  2003

In [32]:
frame.head()

pop   state  year
0  1.5    ohio  2000
1  1.7    ohio  2001
2  3.6    ohio  2002
3  2.4  nevada  2001
4  2.9  nevada  2002

In [37]:
pd.DataFrame(data,columns=['year','halo','pop'])

year halo  pop
0  2000  NaN  1.5
1  2001  NaN  1.7
2  2002  NaN  3.6
3  2001  NaN  2.4
4  2002  NaN  2.9
5  2003  NaN  3.2

In [38]:
frame2 = pd.DataFrame(data,columns=['state','year','pop'],index=
                                    ['one','two','three','four','fivr','six'])
frame2

state  year  pop
one      ohio  2000  1.5
two      ohio  2001  1.7
three    ohio  2002  3.6
four   nevada  2001  2.4
fivr   nevada  2002  2.9
six    nevada  2003  3.2

In [39]:
frame2.columns

Index(['state', 'year', 'pop'], dtype='object')

In [40]:
frame2.index

Index(['one', 'two', 'three', 'four', 'fivr', 'six'], dtype='object')

In [44]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     nevada
fivr     nevada
six      nevada
Name: state, dtype: object

In [45]:
frame2.loc['one']

state    ohio
year     2000
pop       1.5
Name: one, dtype: object

In [46]:
frame2['newcolumn'] = 'new'

In [47]:
frame2

state  year  pop newcolumn
one      ohio  2000  1.5       new
two      ohio  2001  1.7       new
three    ohio  2002  3.6       new
four   nevada  2001  2.4       new
fivr   nevada  2002  2.9       new
six    nevada  2003  3.2       new

In [5]:
pop = {'nevada':{2001:24,2002:33},
       'inter':{2002:44,2003:67},
       'amd':{2004:12,2009:45}}
frame3 = pd.DataFrame(pop)
frame3

amd  inter  nevada
2001   NaN    NaN    24.0
2002   NaN   44.0    33.0
2003   NaN   67.0     NaN
2004  12.0    NaN     NaN
2009  45.0    NaN     NaN

In [6]:
frame3.T

2001  2002  2003  2004  2009
amd      NaN   NaN   NaN  12.0  45.0
inter    NaN  44.0  67.0   NaN   NaN
nevada  24.0  33.0   NaN   NaN   NaN

In [7]:
pdata = {'xlinx':frame3['amd'][:-1],
        'arm':frame3['inter'][:2]}
pd.DataFrame(pdata)

arm  xlinx
2001   NaN    NaN
2002  44.0    NaN
2003   NaN    NaN
2004   NaN   12.0

In [8]:
frame3.index.name = 'year'
frame3.columns.name = 'company'
frame3

company   amd  inter  nevada
year                        
2001      NaN    NaN    24.0
2002      NaN   44.0    33.0
2003      NaN   67.0     NaN
2004     12.0    NaN     NaN
2009     45.0    NaN     NaN

In [9]:
frame3.columns

Index(['amd', 'inter', 'nevada'], dtype='object', name='company')

In [10]:
obj = pd.Series([1,2,3,4],index=['b','c','d','a'])
print(obj)
obj = obj.reindex(['a','b','c','d','e'])
print(obj)

b    1
c    2
d    3
a    4
dtype: int64
a    4.0
b    1.0
c    2.0
d    3.0
e    NaN
dtype: float64


In [13]:
obj3 = pd.Series(['blue','red','green'],index = [0,2,4])
print(obj3)
obj3 = obj3.reindex([0,1,2,3,4,5],method='ffill')
print(obj3)

0     blue
2      red
4    green
dtype: object
0     blue
1     blue
2      red
3      red
4    green
5    green
dtype: object


In [27]:
import numpy as np
obj = pd.Series(np.arange(5),index = ['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [31]:
new_obj = obj.drop('c')
print(obj)
print(new_obj)
print(obj)
obj.drop('c',inplace=True)
print(obj)

a    0
b    1
c    2
d    3
e    4
dtype: int32
a    0
b    1
d    3
e    4
dtype: int32
a    0
b    1
c    2
d    3
e    4
dtype: int32
a    0
b    1
d    3
e    4
dtype: int32


In [32]:
print(obj)

a    0
b    1
d    3
e    4
dtype: int32


In [34]:
obj['a':'d']

a    0
b    1
d    3
dtype: int32

In [35]:
s1 = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s2 = pd.Series([9,8,7,6,5],index = ['a','b','c','g','f'])
s1+s2

a    10.0
b    10.0
c    10.0
d     NaN
e     NaN
f     NaN
g     NaN
dtype: float64

In [37]:
arr = np.arange(12).reshape((3,4))
print(arr)
print(arr-arr[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


In [45]:
frame = pd.DataFrame(np.arange(8).reshape(2,4),index=['t','o'],columns=['5','2','3','4'])
frame.sort_index()

5  2  3  4
o  4  5  6  7
t  0  1  2  3

In [46]:
frame.sort_index(axis=1)

2  3  4  5
t  1  2  3  0
o  5  6  7  4

In [48]:
frame.sort_values(by = '3')

5  2  3  4
t  0  1  2  3
o  4  5  6  7

In [50]:
obj = pd.Series(range(6),index=['a','a','b','b','c','c'])
obj

a    0
a    1
b    2
b    3
c    4
c    5
dtype: int32

In [51]:
obj.index.is_unique

False

In [52]:
obj['a']

a    0
a    1
dtype: int32

In [54]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index = ['a','b','c','d'],
                 columns = ['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [55]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [56]:
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [57]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [58]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [1]:
import pandas_datareader.data as web

In [2]:
all_data = {ticker:web.get_data_yahoo(ticker)
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker:data['Adj Close']
                     for ticker,data in all_data.items()})
volume = pd.DataFrame({ticker:data['Volume']
                      for ticker,data in all_data.items()})

KeyboardInterrupt: 

In [ ]:
returns = price.pct_change()

In [ ]:
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.corr()

In [ ]:
returns.cov()

In [ ]:
returns.corrw(returns.IBM)

In [4]:
obj = pd.Series(['a','a','b','b','b','c'])

In [5]:
uni = obj.unique()

In [6]:
uni

array(['a', 'b', 'c'], dtype=object)

In [8]:
obj.value_counts()

b    3
a    2
c    1
dtype: int64

In [9]:
obj.value_counts(sort=False)

c    1
b    3
a    2
dtype: int64

In [10]:
mask = obj.isin(['b','c'])

In [11]:
mask

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [12]:
obj

0    a
1    a
2    b
3    b
4    b
5    c
dtype: object

In [13]:
obj[mask]

2    b
3    b
4    b
5    c
dtype: object